# Make sure this is set to "kotlinforforge"
modLoader = "kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion = "[4.11,)" # Require at least 4.11.x
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "logo.png"
# optional
#credits="The ExampleMod dev team"
authors = "${mod_authors}"
description = '''${mod_description}'''
[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "tacz"
mandatory = false
versionRange = "[1.1.7,)"
ordering = "AFTER"
side = "BOTH"
